export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          email: string | null;
          username: string | null;
          full_name: string | null;
          home_state: string | null;
          current_state: string | null;
        };
        Insert: {
          id: string;
          created_at?: string;
          updated_at?: string;
          email?: string | null;
          username?: string | null;
          full_name?: string | null;
          home_state?: string | null;
          current_state?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          email?: string | null;
          username?: string | null;
          full_name?: string | null;
          home_state?: string | null;
          current_state?: string | null;
        };
      };
      user_settings: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          default_mileage_rate: number;
          tutoring_tax_reserve_percent: number;
          consulting_tax_reserve_percent: number;
          other_tax_reserve_percent: number;
          w2_annual_income: number | null;
          w2_annual_tax_withheld: number | null;
          home_state: string | null;
          current_state: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          default_mileage_rate?: number;
          tutoring_tax_reserve_percent?: number;
          consulting_tax_reserve_percent?: number;
          other_tax_reserve_percent?: number;
          w2_annual_income?: number | null;
          w2_annual_tax_withheld?: number | null;
          home_state?: string | null;
          current_state?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          default_mileage_rate?: number;
          tutoring_tax_reserve_percent?: number;
          consulting_tax_reserve_percent?: number;
          other_tax_reserve_percent?: number;
          w2_annual_income?: number | null;
          w2_annual_tax_withheld?: number | null;
          home_state?: string | null;
          current_state?: string | null;
        };
      };
      businesses: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          name: string;
          slug: string;
          business_kind: "tutoring" | "consulting" | "other";
          default_tax_reserve_percent: number;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          name: string;
          slug: string;
          business_kind: "tutoring" | "consulting" | "other";
          default_tax_reserve_percent?: number;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          name?: string;
          slug?: string;
          business_kind?: "tutoring" | "consulting" | "other";
          default_tax_reserve_percent?: number;
          is_active?: boolean;
        };
      };
      income_entries: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          business_id: string;
          received_on: string;
          payer_client: string;
          income_category: string;
          gross_amount: number;
          fees_withheld: number;
          net_received: number;
          notes: string | null;
          tax_year: number;
          tax_quarter: number;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          business_id: string;
          received_on: string;
          payer_client: string;
          income_category: string;
          gross_amount: number;
          fees_withheld?: number;
          net_received: number;
          notes?: string | null;
          tax_year: number;
          tax_quarter: number;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          business_id?: string;
          received_on?: string;
          payer_client?: string;
          income_category?: string;
          gross_amount?: number;
          fees_withheld?: number;
          net_received?: number;
          notes?: string | null;
          tax_year?: number;
          tax_quarter?: number;
        };
      };
      expense_entries: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          business_id: string;
          expense_date: string;
          vendor: string;
          expense_category: string;
          description: string;
          amount: number;
          business_use_percent: number;
          deductible_amount: number;
          payment_method: string;
          is_recurring: boolean;
          receipt_path: string | null;
          notes: string | null;
          tax_year: number;
          tax_quarter: number;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          business_id: string;
          expense_date: string;
          vendor: string;
          expense_category: string;
          description: string;
          amount: number;
          business_use_percent?: number;
          deductible_amount: number;
          payment_method: string;
          is_recurring?: boolean;
          receipt_path?: string | null;
          notes?: string | null;
          tax_year: number;
          tax_quarter: number;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          business_id?: string;
          expense_date?: string;
          vendor?: string;
          expense_category?: string;
          description?: string;
          amount?: number;
          business_use_percent?: number;
          deductible_amount?: number;
          payment_method?: string;
          is_recurring?: boolean;
          receipt_path?: string | null;
          notes?: string | null;
          tax_year?: number;
          tax_quarter?: number;
        };
      };
      mileage_entries: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          business_id: string;
          trip_date: string;
          purpose: string;
          origin_location: string;
          destination_location: string;
          miles: number;
          mileage_rate: number;
          deductible_value: number;
          is_round_trip: boolean;
          notes: string | null;
          tax_year: number;
          tax_quarter: number;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          business_id: string;
          trip_date: string;
          purpose: string;
          origin_location: string;
          destination_location: string;
          miles: number;
          mileage_rate: number;
          deductible_value: number;
          is_round_trip?: boolean;
          notes?: string | null;
          tax_year: number;
          tax_quarter: number;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          business_id?: string;
          trip_date?: string;
          purpose?: string;
          origin_location?: string;
          destination_location?: string;
          miles?: number;
          mileage_rate?: number;
          deductible_value?: number;
          is_round_trip?: boolean;
          notes?: string | null;
          tax_year?: number;
          tax_quarter?: number;
        };
      };
      personal_cashflow_entries: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          entry_date: string;
          category: string;
          subcategory: string | null;
          amount: number;
          notes: string | null;
          entry_month: number;
          entry_year: number;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          entry_date: string;
          category: string;
          subcategory?: string | null;
          amount: number;
          notes?: string | null;
          entry_month: number;
          entry_year: number;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          entry_date?: string;
          category?: string;
          subcategory?: string | null;
          amount?: number;
          notes?: string | null;
          entry_month?: number;
          entry_year?: number;
        };
      };
      housing_deduction_entries: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          entry_date: string;
          category: string;
          detail: string | null;
          amount: number;
          home_state: string | null;
          home_square_feet: number | null;
          office_square_feet: number | null;
          notes: string | null;
          entry_month: number;
          entry_year: number;
          legacy_personal_cashflow_entry_id: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          entry_date: string;
          category: string;
          detail?: string | null;
          amount: number;
          home_state?: string | null;
          home_square_feet?: number | null;
          office_square_feet?: number | null;
          notes?: string | null;
          entry_month: number;
          entry_year: number;
          legacy_personal_cashflow_entry_id?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          entry_date?: string;
          category?: string;
          detail?: string | null;
          amount?: number;
          home_state?: string | null;
          home_square_feet?: number | null;
          office_square_feet?: number | null;
          notes?: string | null;
          entry_month?: number;
          entry_year?: number;
          legacy_personal_cashflow_entry_id?: string | null;
        };
      };
      housing_monthly_entries: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          entry_date: string;
          base_rent: number;
          parking: number;
          utilities: number;
          insurance: number;
          maintenance: number;
          home_state: string | null;
          home_square_feet: number | null;
          office_square_feet: number | null;
          notes: string | null;
          entry_month: number;
          entry_year: number;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          entry_date: string;
          base_rent?: number;
          parking?: number;
          utilities?: number;
          insurance?: number;
          maintenance?: number;
          home_state?: string | null;
          home_square_feet?: number | null;
          office_square_feet?: number | null;
          notes?: string | null;
          entry_month: number;
          entry_year: number;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          entry_date?: string;
          base_rent?: number;
          parking?: number;
          utilities?: number;
          insurance?: number;
          maintenance?: number;
          home_state?: string | null;
          home_square_feet?: number | null;
          office_square_feet?: number | null;
          notes?: string | null;
          entry_month?: number;
          entry_year?: number;
        };
      };
      tax_reserves: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          business_id: string;
          reserve_date: string;
          source_income_amount: number;
          reserve_percent: number;
          reserve_amount: number;
          was_transferred: boolean;
          counts_as_federal_estimated_payment: boolean;
          counts_as_state_estimated_payment: boolean;
          destination_account: string | null;
          notes: string | null;
          tax_year: number;
          tax_quarter: number;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          business_id: string;
          reserve_date: string;
          source_income_amount: number;
          reserve_percent: number;
          reserve_amount: number;
          was_transferred?: boolean;
          counts_as_federal_estimated_payment?: boolean;
          counts_as_state_estimated_payment?: boolean;
          destination_account?: string | null;
          notes?: string | null;
          tax_year: number;
          tax_quarter: number;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          business_id?: string;
          reserve_date?: string;
          source_income_amount?: number;
          reserve_percent?: number;
          reserve_amount?: number;
          was_transferred?: boolean;
          counts_as_federal_estimated_payment?: boolean;
          counts_as_state_estimated_payment?: boolean;
          destination_account?: string | null;
          notes?: string | null;
          tax_year?: number;
          tax_quarter?: number;
        };
      };
      tax_planning_profiles: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          tax_year: number;
          filing_status: "single" | "married_filing_jointly" | "married_filing_separately" | "head_of_household";
          home_state: string | null;
          prior_year_agi: number | null;
          prior_year_federal_total_tax: number | null;
          prior_year_state_total_tax: number | null;
          annual_w2_withholding_expected: number;
          annual_other_withholding_expected: number;
          tax_season_reviewed_at: string | null;
          notes: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          tax_year: number;
          filing_status?: "single" | "married_filing_jointly" | "married_filing_separately" | "head_of_household";
          home_state?: string | null;
          prior_year_agi?: number | null;
          prior_year_federal_total_tax?: number | null;
          prior_year_state_total_tax?: number | null;
          annual_w2_withholding_expected?: number;
          annual_other_withholding_expected?: number;
          tax_season_reviewed_at?: string | null;
          notes?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          tax_year?: number;
          filing_status?: "single" | "married_filing_jointly" | "married_filing_separately" | "head_of_household";
          home_state?: string | null;
          prior_year_agi?: number | null;
          prior_year_federal_total_tax?: number | null;
          prior_year_state_total_tax?: number | null;
          annual_w2_withholding_expected?: number;
          annual_other_withholding_expected?: number;
          tax_season_reviewed_at?: string | null;
          notes?: string | null;
        };
      };
      home_office_profiles: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          tax_year: number;
          home_state: string | null;
          method_preference: "auto" | "simplified" | "regular";
          exclusive_use_confirmed: boolean;
          principal_place_confirmed: boolean;
          home_square_feet: number | null;
          office_square_feet: number | null;
          qualifying_months: number;
          monthly_rent: number;
          monthly_utilities: number;
          monthly_internet: number;
          monthly_renters_insurance: number;
          monthly_home_maintenance: number;
          direct_office_expenses: number;
          notes: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          tax_year: number;
          home_state?: string | null;
          method_preference?: "auto" | "simplified" | "regular";
          exclusive_use_confirmed?: boolean;
          principal_place_confirmed?: boolean;
          home_square_feet?: number | null;
          office_square_feet?: number | null;
          qualifying_months?: number;
          monthly_rent?: number;
          monthly_utilities?: number;
          monthly_internet?: number;
          monthly_renters_insurance?: number;
          monthly_home_maintenance?: number;
          direct_office_expenses?: number;
          notes?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          tax_year?: number;
          home_state?: string | null;
          method_preference?: "auto" | "simplified" | "regular";
          exclusive_use_confirmed?: boolean;
          principal_place_confirmed?: boolean;
          home_square_feet?: number | null;
          office_square_feet?: number | null;
          qualifying_months?: number;
          monthly_rent?: number;
          monthly_utilities?: number;
          monthly_internet?: number;
          monthly_renters_insurance?: number;
          monthly_home_maintenance?: number;
          direct_office_expenses?: number;
          notes?: string | null;
        };
      };
      home_office_space_periods: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          effective_from: string;
          effective_to: string | null;
          home_square_feet: number;
          office_square_feet: number;
          notes: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          effective_from: string;
          effective_to?: string | null;
          home_square_feet: number;
          office_square_feet: number;
          notes?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          effective_from?: string;
          effective_to?: string | null;
          home_square_feet?: number;
          office_square_feet?: number;
          notes?: string | null;
        };
      };
      w2_paychecks: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          pay_date: string;
          employer: string;
          gross_pay: number;
          federal_tax_withheld: number;
          state_tax_withheld: number;
          social_security_withheld: number;
          medicare_withheld: number;
          other_pre_tax_deductions: number;
          other_post_tax_deductions: number;
          net_pay: number;
          state_code: string | null;
          notes: string | null;
          tax_year: number;
          tax_quarter: number;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          pay_date: string;
          employer: string;
          gross_pay: number;
          federal_tax_withheld?: number;
          state_tax_withheld?: number;
          social_security_withheld?: number;
          medicare_withheld?: number;
          other_pre_tax_deductions?: number;
          other_post_tax_deductions?: number;
          net_pay: number;
          state_code?: string | null;
          notes?: string | null;
          tax_year: number;
          tax_quarter: number;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          pay_date?: string;
          employer?: string;
          gross_pay?: number;
          federal_tax_withheld?: number;
          state_tax_withheld?: number;
          social_security_withheld?: number;
          medicare_withheld?: number;
          other_pre_tax_deductions?: number;
          other_post_tax_deductions?: number;
          net_pay?: number;
          state_code?: string | null;
          notes?: string | null;
          tax_year?: number;
          tax_quarter?: number;
        };
      };
      academy_intake_submissions: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          parent_full_name: string;
          parent_email: string;
          parent_phone: string | null;
          student_first_name: string;
          grade: string;
          subject: string;
          goals: string;
          session_format: string;
          status: string;
          accepted_client_agreement: boolean;
          accepted_terms: boolean;
          accepted_privacy: boolean;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          parent_full_name: string;
          parent_email: string;
          parent_phone?: string | null;
          student_first_name: string;
          grade: string;
          subject: string;
          goals: string;
          session_format: string;
          status?: string;
          accepted_client_agreement?: boolean;
          accepted_terms?: boolean;
          accepted_privacy?: boolean;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          parent_full_name?: string;
          parent_email?: string;
          parent_phone?: string | null;
          student_first_name?: string;
          grade?: string;
          subject?: string;
          goals?: string;
          session_format?: string;
          status?: string;
          accepted_client_agreement?: boolean;
          accepted_terms?: boolean;
          accepted_privacy?: boolean;
        };
      };
      academy_testimonials: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          first_name: string;
          last_name: string;
          class_year: string;
          tutor_name: string;
          subject: string;
          impression: string | null;
          video_path: string | null;
          video_url: string | null;
          moderation_status: string;
          is_published: boolean;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          first_name: string;
          last_name: string;
          class_year: string;
          tutor_name: string;
          subject: string;
          impression?: string | null;
          video_path?: string | null;
          video_url?: string | null;
          moderation_status?: string;
          is_published?: boolean;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          first_name?: string;
          last_name?: string;
          class_year?: string;
          tutor_name?: string;
          subject?: string;
          impression?: string | null;
          video_path?: string | null;
          video_url?: string | null;
          moderation_status?: string;
          is_published?: boolean;
        };
      };
      assets: {
        Row: {
          id: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          business_id: string;
          asset_name: string;
          purchase_date: string;
          cost: number;
          business_use_percent: number;
          business_use_amount: number;
          asset_category: string;
          notes: string | null;
        };
        Insert: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          business_id: string;
          asset_name: string;
          purchase_date: string;
          cost: number;
          business_use_percent?: number;
          business_use_amount: number;
          asset_category: string;
          notes?: string | null;
        };
        Update: {
          id?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          business_id?: string;
          asset_name?: string;
          purchase_date?: string;
          cost?: number;
          business_use_percent?: number;
          business_use_amount?: number;
          asset_category?: string;
          notes?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      business_kind: "tutoring" | "consulting" | "other";
    };
    CompositeTypes: Record<string, never>;
  };
};
